version: "3.9"
services:
    nginx-mera:
        image: localhost:5000/project/app
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
            resources:
                limits:
                    memory: 128M
                reservations:
                    memory: 128M
        networks:
            - test
networks:
    test:
        name: test
